### ISSUE TITLE
No longer compile with current spirv-cross git

### ISSUE THREAD

**Issue by shinchiro** [rossy/crossc#3]
I'm already told in IRC but probably you're busy these days.

SPIRV-Cross made major refactors which made crossc failed to compile. Probably because of this commit:
https://github.com/KhronosGroup/SPIRV-Cross/commit/5bcf02f7c940ce98c86bedf265589722cedd58ed
Take a look at it when you've time :^)

**Comment by rossy** [comment]
Thanks for reporting. It seems like the only problem was the new files missing from the build, so it should work now.

**Comment by shinchiro** [comment]
Yeah, can confirm its fixed. Thanks a lot
